name: 'KA3005p-Dev'
description: 'Setup tooling for KA3005p workspace'

runs:

  using: "composite"
  steps:

    - name: Setup Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt,clippy

    - name: Install just
      shell: bash
      run: |
        cargo install just

    - name: Install mdbook
      shell: bash
      run: |
        cargo install just

